package com.example.mongodbspringdemo.bean.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   数据源管理
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table datasource
 */
@Document
@Data
@NoArgsConstructor
@AllArgsConstructor
public class DataSource implements Serializable {

    @Id
    private String dcId;

    private String dbUuid;

    private String dbInstance;

    private String dbName;

    private String dbType;

    private String dbIp;

    private String dbPort;

    private String account;

    private String password;

    private LocalDateTime updateTime;

    private String isDelete;

    private String createUser;

    private LocalDateTime createTime;

    private String custom1;

    private String custom;

}